// blog/patterns/resum/src/routes/posts/[id]/index.jsx
import { component$, useSignal, useStylesScoped$ } from "@builder.io/qwik"
import { Link, routeAction$, routeLoader$, useLocation, useNavigate } from "@builder.io/qwik-city"
import { db } from "~/utils/db.js"
import MarkdownIt from "markdown-it"
import style from "./index.css?inline"
import Comments from "~/routes/posts/[id]/comments.jsx"

export const usePost = routeLoader$(async ({ params, status }) => {
    const { rows } = await db.query(
        `select post.id,
                title,
                author,
                content,
                post.created,
                post.modified,
                categoryid,
                category.name as category
         from post
                  join category on post.categoryid = category.id
         where post.id = $1`, [params.id])

    if (rows.length === 0)
        status(404)

    return rows[0]
})

export const useComments = routeLoader$(async event => {
    const { rows } = await db.query(
        `select id, author, content, created, modified
         from Comment
         where postid = $1
         order by created`, [event.params.id])
    return rows
})

export const useDeletePost = routeAction$(async (_, { params }) => {
    db.query("delete from post where id = $1", [params.id])
    return { ok: true }
})

export const useCreateComment = routeAction$(async (comment, { params, fail }) => {
    const keys = ["author", "content"]
    for (const key of keys)
        if (!comment[key] || !comment[key].length)
            return fail(422, {
                error: `${key} cannot be empty!`,
            })

    const { rows } = await db.query(
        "insert into comment (postid, author, content) values ($1, $2, $3) returning id",
        [params.id, ...keys.map(key => comment[key])])

    return { id: rows[0].id, ok: true }
})

export default component$(() => {
    useStylesScoped$(style)

    const { params } = useLocation()

    const post = usePost()
    const comments = useComments()

    const md = new MarkdownIt({ linkify: true })

    function formatDate1(dateStr) {
        return new Date(dateStr).toLocaleDateString("en-UK",
            { weekday: "long", day: "numeric", month: "long", year: "numeric" })
    }

    function formatDate2(dateStr) {
        return new Date(dateStr).toLocaleString("en-GB",
            { day: "numeric", month: "long", year: "numeric", hour: "numeric", minute: "2-digit" })
    }

    const createComment = useCreateComment()
    const formRef = useSignal()

    const deletePost = useDeletePost()
    const nav = useNavigate()

    return (
        <>
            <div class="container">
                {post.value ? <>
                        <header class="post-header">
                            <h1>{post.value.title}</h1>

                            <Link class="button" href={`/categories/${post.value.categoryid}`}>
                                #{post.value.category}
                            </Link>
                            <p class="author">by <span class="name">{post.value.author}</span></p>
                            <p class="date">
                                {formatDate1(post.value.created)}
                                {post.value.created.getTime() !== post.value.modified.getTime() &&
                                    <span>(last modified {formatDate2(post.value.modified)})</span>}
                            </p>
                            <div class="actions">
                                <Link class="button" href={`/posts/${params.id}/edit`}>Edit post</Link>
                                &nbsp;
                                <button onClick$={async () => {
                                    if (confirm("Are you sure you want to delete this post? (No undo)")) {
                                        const { value: { ok } } = await deletePost.submit()
                                        if (ok) nav("/posts")
                                    }
                                }}>
                                    Delete post
                                </button>
                            </div>
                        </header>

                        <div class="content" dangerouslySetInnerHTML={md.render(post.value.content)}></div>

                        <footer class="post-footer">
                            <Comments comments={comments} action={createComment}/>
                        </footer>
                    </>
                    : <p>Post not found.</p>}
            </div>
        </>
    )
})

// blog/patterns/iso/pages/posts/[id]/index.vue
<script setup>
import MarkdownIt from "markdown-it"

const route = useRoute()

const { data: post } = await useFetch("/api/posts/" + route.params.id)

const md = new MarkdownIt({ linkify: true })

function formatDate1(dateStr) {
  return new Date(dateStr).toLocaleDateString("en-UK",
      { weekday: "long", day: "numeric", month: "long", year: "numeric" })
}

function formatDate2(dateStr) {
  return new Date(dateStr).toLocaleString("en-GB",
      { day: "numeric", month: "long", year: "numeric", hour: "numeric", minute: "2-digit" })
}

async function deletePost() {
  if (confirm("Are you sure you want to delete this post? (No undo)")) {
    await $fetch("/api/posts/" + route.params.id, { method: "DELETE" })
    navigateTo("/posts")
  }
}

const comment = { author: null, content: null }
const error = ref(null)

async function createComment() {
  await $fetch(`/api/posts/${route.params.id}/comments`, { method: "POST", body: comment })
  post.value.comments.push({ ...comment, created: new Date() })
  comment.author = null
  comment.content = null
}
</script>

<template>
  <div class="container">
    <header class="post-header">
      <h1>{{ post.title }}</h1>

      <NuxtLink class="button" :to="`/categories/${post.categoryid}`">
        #{{ post.category }}
      </NuxtLink>
      <p class="author">by <span class="name">{{ post.author }}</span></p>
      <p class="date">
        {{ formatDate1(post.created) }}
        <span v-if="post.created !== post.modified">(last modified {{ formatDate2(post.modified) }})</span>
      </p>
      <div class="actions">
        <NuxtLink class="button" :to="`/posts/${$route.params.id}/edit`">Edit post</NuxtLink>
        <button @click="deletePost">Delete post</button>
      </div>
    </header>

    <div class="content" v-html="md.render(post.content)"></div>

    <footer class="post-footer">
      <template v-if="post.comments.length > 0">
        <h2>Comments</h2>
        <div class="comments">
          <div v-for="comment in post.comments" class="comment">
            <header>
              <div class="author">{{ comment.author }}</div>
              <div class="date">{{ formatDate1(comment.created) }}</div>
            </header>
            <div class="message">{{ comment.content }}</div>
          </div>
        </div>
      </template>
      <p v-else>No comments yet</p>


      <form @submit.prevent="createComment">
        <h3>Leave a comment</h3>

        <p v-if="error" class="error">{{ error }}</p>

        <label for="name">Your name</label>
        <input id="name" minlength="1" required v-model="comment.author">
        <label for="message">Message</label>
        <textarea id="message" rows="4" minlength="1" v-model="comment.content"></textarea>
        <div class="actions">
          <button type="submit">Send</button>
        </div>
      </form>
    </footer>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
}

.container > * {
  width: 100%;
}

.post-header, .post-footer {
  background: aliceblue;
  overflow: auto;
  border-bottom: 1px cornflowerblue solid;
  border-top: 1px cornflowerblue solid;
  margin: 0 -1.5em;
  padding: 0 1.5em;
}

.post-header .actions {
  text-align: right;
  margin-bottom: 1em;
}

.content {
  flex-grow: 1;
  font-family: serif;
  max-width: 800px;
  margin: 2em auto 3em;
}

.content:deep(p) {
  text-align: justify;
}

.content:deep(img) {
  max-width: min(600px, 100%);
  max-height: 600px;
  margin: auto;
  display: block;
}

.post-footer :is(p, h2, h3) {
  text-align: center;
}

.comments {
  display: flex;
  flex-direction: column;
  gap: 1em;
  width: min(600px, 100%);
  margin: auto;
}

.comment {
  padding: 1em;
  border-radius: 1em;
  background: white;
  border: 1px solid lightgrey;
}

.comment header {
  font-weight: bold;
  display: flex;
  justify-content: space-between;
  margin-bottom: 1em;
}

form {
  display: flex;
  flex-direction: column;
  gap: 0.5em;
  width: min(600px, 100%);
  margin: 0 auto 2em;
}

form label {
  font-weight: bold;
}

form textarea {
  resize: vertical;
}

form .actions {
  text-align: right;
}

form input, form textarea {
  padding: 0.5em;
}
</style>
