// blog/patterns/iso/components/post-form.vue
<script setup>
defineProps({
  post: { type: Object, required: true },
  newPost: { type: Boolean, default: false },
  error: { type: String, default: null },
})

const { data: categories } = await useFetch("/api/categories")
</script>

<template>
  <form>
    <p v-if="error" class="error">{{ error }}</p>
    <label>
      Post title
      <input type="text" required minlength="1" autofocus v-model="post.title">
    </label>
    <label>
      Author name
      <input type="text" required minlength="1" v-model="post.author">
    </label>
    <label>
      Category
      <select v-model="post.categoryid" required>
        <option v-if="newPost" disabled selected value> -- please select --</option>
        <option v-for="category in categories" :value="category.id">{{ category.name }}</option>
      </select>
    </label>
    <label>
      Body
      <textarea rows="16" required minlength="1" v-model="post.content"></textarea>
    </label>
    <button type="submit">{{ newPost ? "Create" : "Update" }}</button>
  </form>
</template>

<style scoped>
form {
  display: flex;
  flex-direction: column;
  gap: 1em;
}

label {
  display: flex;
  flex-direction: column;
  font-weight: bold;
  gap: 0.5em;
}

input, textarea, button, select {
  padding: 0.5em;
}

textarea {
  resize: vertical;
}

button, select {
  cursor: pointer;
}
</style>

// blog/patterns/resum/src/components/post-form.jsx
import { component$, useStylesScoped$ } from "@builder.io/qwik"
import { db } from "~/utils/db.js"
import { Form, server$, useNavigate } from "@builder.io/qwik-city"
import style from "./post-form.css?inline"

const fetchCategories = server$(async () => {
    const { rows } = await db.query("select category.id, name from category")
    return rows
})

export default component$(({ post, newPost = false, action }) => {
    useStylesScoped$(style)
    const nav = useNavigate()

    return <Form action={action}
                 onSubmitCompleted$={() => action.value?.ok && nav("/posts/" + action.value.id)}>
        {action.value?.failed && <p class="error">{action.value.error}</p>}
        <label>
            Post title
            <input type="text" required minLength="1" autofocus name="title" value={post.value.title}/>
        </label>
        <label>
            Author name
            <input type="text" required minLength="1" name="author" value={post.value.author}/>
        </label>
        <label>
            Category
            <select name="categoryid" required>
                {newPost &&
                    <option disabled selected value> -- please select --</option>}
                {fetchCategories().then(categories => categories.map(category =>
                    <option value={category.id} key={category.id} selected={category.id === post.value.categoryid}>
                        {category.name}
                    </option>))}
            </select>
        </label>
        <label>
            Body
            <textarea rows="16" required minLength="1" name="content">{post.value.content}</textarea>
        </label>
        <button type="submit">{newPost ? "Create" : "Update"}</button>
    </Form>
})
